### ISSUE TITLE
Nothing seems to happen on the GNOME 42 desktop

### ISSUE THREAD

**Issue by johnblommers** [jszczerbinsky/lwp#1]
Even with disabling GNOME extensions, running `lwp` produces no parallax effect or any effect. It emits no messages. The installation process went smoothly and without incident or error.

I do have a wallpaper of my own set.

My system is PopOS 22.04 with the GNOME desktop. It's an Ubuntu derivative. The CPU/GPU is AMD Ryzen 5 2550H with Radeon Vega Mobile Gfx graphics. 

Is `lwp` intended for more basic desktop environment perhaps?

Update. It seems so. When I login with the fvwm desktop environment `lwp` works exactly as intended. Other than the mouse disappearing when its not inside another application window.

**Comment by CraigglesO** [comment]
I am also using GNOME 42 via the latest ubuntu and my screen lags, but nothing else happens... AMD CPU and Nvidia GPU (1080Ti)

**Comment by jszczerbinsky** [comment]
I'm not sure why wallpaper doesn't work, but I think GNOME might override the root window. Try fully disabling the wallpaper in GNOME.

Mouse cursor bug can be easly fixed by using xsetroot after running lwp

**Comment by johnblommers** [comment]
I'm pretty sure GNOME takes over the root window. I've tried using the dconf editor to delete the wallpaper but the background just turns black. `lwp` is no more able to impact the background than `xsetroot` unfortunately.

At this juncture I've not found a way around this problem with GNOME.

**Comment by Baumistlustig** [comment]
Same problem here, would appreciate a solution!

**Comment by Baumistlustig** [comment]
Any updates, or an idea on how to fix it temporarily?

**Comment by jszczerbinsky** [comment]
After so many time I found this pull request in similar project https://github.com/glouw/paperview/pull/22 and it's a solution to this issue. I tested this with picom compositor and it works fine. The issue will be fixed in next release.

**Comment by jszczerbinsky** [comment]
I think I found a partial solution. I've tested it with `picom` compositor and it works fine, but I'm not sure, that it doesn't lead to some visual bugs.

There is a pull request in similar project (https://github.com/glouw/paperview/pull/22), that fixes the problem. Unfortunately when I was testing it on GNOME it still didn't work, but PR description clearly says, that this works on GNOME as well, so I will keep testing it.

**Comment by jszczerbinsky** [comment]
I think I found a solution. I've made some changes, tested lwp with picom compositor and then with GNOME and it works fine.
New release is comming and it will have this fixed. I'm closing this issue, but in case of any related problems, just reopen it.

**Comment by jszczerbinsky** [comment]
To make lwp run with a compositor or GNOME, You just have to set `reload_rootwindow=1` in the config file
