### ISSUE TITLE
Movement "multiplier"

### ISSUE THREAD

**Issue by OshidaBCF** [jszczerbinsky/lwp#10]
After testing the sensitivity per layer, i noticed that i need to divide the value i had by a 1000

Could it be possible to have a "movementMultiplier" for all the movements, so my script can just write the same value without dividing

**Comment by jszczerbinsky** [comment]
Do You mean, that setting some value to global movement works different than setting the same value to per layer movement?

**Comment by OshidaBCF** [comment]
No, i have 18 different values, that are integers, usually between +/- 20, but using those number in the tool make it slightly broken.

Found out that i actually had to divide the number i had by 1920, which for number like 3 give out really long value.


What i suggest is a "global multiplier" value so you can put number a bit smaller and just scale them by 1/2000, could be a global "scaling" factor.

**Comment by jszczerbinsky** [comment]
I think it may be a little confusing. Sensitivity value represents exactly how many times more than the cursor distance from the center should the layer move and in my opinion it should stay that way.
