### ISSUE TITLE
Make mouse position stop at screen edge

### ISSUE THREAD

**Issue by OshidaBCF** [jszczerbinsky/lwp#11]
I have two screens and when the mouse goes to the other screen, the mouse position is now too high for my wallpaper to "work"
could it be possible to limit the position between the xywh values of each monitor (no overflow)

So putting the mouse between the two screen would make my left screen "look" right, and the right one "look" left, but not further

**Comment by jszczerbinsky** [comment]
Yeah, I also noticed it. I'm going to fix this soon

**Comment by OshidaBCF** [comment]
Thank you
