### ISSUE TITLE
Mouse position is off by 390 px from the left

### ISSUE THREAD

**Issue by OshidaBCF** [jszczerbinsky/lwp#13]
Now that my wallpaper is working properly, i noticed the "correct" values it's supposed to work within (0, 1920) doesn't start at position 0 but at 390 px, i do not know if it's related to the "monintorX_1=-390" value, 

is this a mistake from my part ?

**Comment by jszczerbinsky** [comment]
Yes, it's because of monitorX, it will be fixed soon by new configuration feature, that will make it possible to set wallpaper position without changing position of the monitor

**Comment by OshidaBCF** [comment]
Brilliant.
