### ISSUE TITLE
Add possibility for different wallpaper per monitors

### ISSUE THREAD

**Issue by OshidaBCF** [jszczerbinsky/lwp#24]
Now that all the things i needed work on one screen, it would nice if we could have a different wallpaper for each screen.

**Comment by jszczerbinsky** [comment]
Awesome idea, I will definitely work on this soon.

**Comment by OshidaBCF** [comment]
This is "slightly "related to #25 as it would make the selection easier for multiple wallpaper, as you wouldn't need to have "twice" the config.
