### ISSUE TITLE
Easier wallpaper "selection"

### ISSUE THREAD

**Issue by OshidaBCF** [jszczerbinsky/lwp#25]
Instead of using 1 config file to select the image folder and list the settings, it would be better to have 1 config file "for" the wallpaper, like sensitivity, count and smooth.

And a "general" config that would say what wallpaper goes where, the dimension of the monitors and their count.

the general one would contain the path for the wallpaper config file (which is in the same folders as the images it needs)

**Comment by jszczerbinsky** [comment]
Sounds good, these wallpaper configs could be inside a wallpaper directory. This would make it easier to share wallpapers, because their behavior would be already configured.

**Comment by OshidaBCF** [comment]
Indeed

**Comment by jszczerbinsky** [comment]
Done, check out new release

**Comment by OshidaBCF** [comment]
thanks a lot

**Comment by jszczerbinsky** [comment]
I'm currently creating a Discord for this project, You can join and share some wallpapers there if You want: https://discord.gg/gHpbkXJD
