### ISSUE TITLE
Larger default wallpaper

### ISSUE THREAD

**Issue by mholt** [jszczerbinsky/lwp#28]
My monitor is 5120x1440. I really like the default wallpaper, but when I scale up the default wallpaper in the config, it looks stretched and pixelated:

![image](https://user-images.githubusercontent.com/1128849/221097566-a1adbe40-b776-430e-bb9f-37f906c2b213.png)

I realize my display is much wider than most have (it's the same physical size as two 27" monitors side-by-side though), so I wouldn't mind if the image gets cropped. But it'd be nice if it wasn't pixelated. Any thoughts?

PS. This is a fun project, and was so easy to set up and use. Thanks!

**Comment by jszczerbinsky** [comment]
Set `monitor1_wallpaper_w` and `monitor2_wallpaper_h` to be the same ratio as a wallpaper (16:9), it will be cropped, but You can adjust the wallpaper position in Y axis with `monitor1_wallpaper_y` and try to center the wallpaper.

Unfortunately there is no way to make this setup not pixelated, You would have to use wallpaper with higher resolution. I'm going to add some more default wallpapers soon, including the one, that will work on widescreen

**Comment by jszczerbinsky** [comment]
I've designed new default wallpaper and created it in 3 variants: `fullhd`, `4k`, `8k`. Fullhd is going to be default one, installed with the program. I decided to not ship `4k` and `8k` with lwp by defualt, because they are heavy, so they  are available on our Discord server instead.

**Comment by mholt** [comment]
Perfect, thanks! Got those suggestions working along with the higher-res wallpaper.
