### ISSUE TITLE
not covering the full desktop

### ISSUE THREAD

**Issue by anupamjaiswall** [jszczerbinsky/lwp#34]
![see my desktop](https://user-images.githubusercontent.com/65376821/221329631-07f60f8a-6fd1-43d2-849c-28c47ecfff97.png)

Its not covering the whole desktop area, also provide the instructions to remove this program from the computer(btw I've already done, just suggesting you).

**Comment by jszczerbinsky** [comment]
Are You using display scaling?

**Comment by anupamjaiswall** [comment]
![image](https://user-images.githubusercontent.com/65376821/221333484-9ce17e45-b941-4446-8aef-5e88e85ba240.png)
I tried at 100% scaling but that also did't work.

neither using scaling nor using external monitor. And also not sharing my mouse and keyboard using barrier.

**Comment by akudan** [comment]
Having the same issue here. The wallpaper viewport size doesn't seem to be affected by the monitor or resolution size settings.

**Comment by jszczerbinsky** [comment]
@anupamjaiswall, it should work, but You have to restart `lwp` first

125% scaling:
![Zrzut ekranu (9)](https://user-images.githubusercontent.com/38699473/221354532-5715fb24-04e3-4af1-b73d-44038f8b4437.png)

100% scaling (after restarting):
![Zrzut ekranu (10)](https://user-images.githubusercontent.com/38699473/221354541-5eff755a-db63-4793-9501-26c5ffc18c27.png)

**Comment by jszczerbinsky** [comment]
For now there is no other way to do it. I'm leaving this issue open until there is some better solution

**Comment by anupamjaiswall** [comment]
Thanks, it worked.

**Comment by jszczerbinsky** [comment]
Fixed it, changes will be available in next release (v1.7)
