### ISSUE TITLE
Would you like some more demos?

### ISSUE THREAD

**Issue by ajw287** [jszczerbinsky/lwp#42]
Cool project!   I saw on hacker news,  thought it was really cool and had a play around.  I made some wallpapers; one using an underwater photo that I took  and one with corporate branding...

  I wondered if you would like either of these as demos?

This is a small version of the original file, fish float around in the wallpaper:
![RIMG3269-sml](https://user-images.githubusercontent.com/35962586/222280883-feaaf811-f60c-4549-b685-0d93897bf201.JPG)

**Comment by jszczerbinsky** [comment]
That's awesome! You can upload this wallpaper to our [discord](https://discord.gg/gHpbkXJD) i might use the one with fish in the demo in the future.

**Comment by ajw287** [comment]
Could you send the invite again?  It seems to have timed out.

**Comment by jszczerbinsky** [comment]
https://discord.gg/JmkCqjYFQa
