### ISSUE TITLE
Does not seem to work for me

### ISSUE THREAD

**Issue by khorchanov** [jszczerbinsky/lwp#58]
Hello, seems to be a very cool project.

But does not work for me at all neither in Ubuntu nor in Windows 11.
I mean the program is launched but wallpaper not changed. 

PS : I'm in multiple monitors

**Comment by jszczerbinsky** [comment]
It's probably because of non-default monitors position. You can check the current position of each monitor using `xrandr` on Linux.

**Comment by jszczerbinsky** [comment]
I found out this was a bug though. Fixed in [latest release](https://github.com/jszczerbinsky/lwp/releases/tag/v2.0.0)
