### ISSUE TITLE
MacOS Compatibility?

### ISSUE THREAD

**Issue by mayurankv** [jszczerbinsky/lwp#6]
Would this work on MacOS?

**Comment by jszczerbinsky** [comment]
Unfortunately no :/
At least for now

**Comment by pranavburnwal** [comment]
+1 if it comes in future.

**Comment by jszczerbinsky** [comment]
I'm going to make this work on MacOS too

**Comment by dginovker** [comment]
I would be very surprised if you could get this working on MacOS. It's much more locked down and doesn't have libraries similar to SDL2

**Comment by SplittyDev** [comment]
@dginovker That's plain out wrong. SDL2 works just fine on macOS, and there are ways to make it work.

**Comment by SplittyDev** [comment]
@jszczerbinsky I've started work on adding macOS support in https://github.com/jszczerbinsky/lwp/pull/31, but there are still a few things that need to be done. Would be great if you could have a look and tell me what you think

**Comment by jszczerbinsky** [comment]
@SplittyDev That's awesome, I will check this out, but first I want to close other issues and I also have to install macOS VM

**Comment by jszczerbinsky** [comment]
Thanks to @SplittyDev  we finally have macOS support! The next release will be available for this platform.
