### ISSUE TITLE
Only I have problem with this program?

### ISSUE THREAD

**Issue by TedAlter** [jszczerbinsky/lwp#61]
I need to edit the config file in main file. Can I get an example of filing filepath to walpaper? (Windows 10)

**Comment by jszczerbinsky** [comment]
Sorry for late response, I didn't have much time lately.
Here is an example of setting wallpaper path: 

`monitor1_wallpaper=C:\path\to\dir`

`dir` is a directory, which contains `wallpaper.cfg` and each layer's `.bmp` file. 
Also make sure You are using backslashes (`\`) instead of slashes (`/`).
