### ISSUE TITLE
Make smoothing work on a sub-pixel level.

### ISSUE THREAD

**Issue by BombchuLink** [jszczerbinsky/lwp#69]
Movements are choppy for layers with low movement speeds, and move full pixels at a time when you move the mouse slowly.

The primary reason I installed this was just to have one background layer that moves a few pixels as you move the mouse across the screen, but I discovered that the movements are not smooth and instead snap to the nearest pixel.

Smoothing doesn't really help, since it actually speeds up movement, and requires a base speed to be decently high enough to work. It doesn't do any processing on a sub pixel level to keep things looking nice.

**Comment by jszczerbinsky** [comment]
Hello, thank You for Your suggestion.

Currently I am a little busy creating other enhancements (primarily the configuration window), but I'll try to find some solution to this issue after finishing my current work.
