### ISSUE TITLE
Add possibility for multiple "sensitivity"

### ISSUE THREAD

**Issue by OshidaBCF** [jszczerbinsky/lwp#7]
I am trying to make some parallax wallpapers, i have a dozen layers per wallpaper, but each one of them have a different "sensitivity"
i found the exact "formula" for the position of each image according to the mouse position.

the formula i use for the x position of the upper left corner of each image is (screenWidth * (cursorPosXPercent - 50) / 100 * sensitivity)

Could it be possible to add a way to give each layer a number ?

**Comment by jszczerbinsky** [comment]
Sure, I can do it

**Comment by OshidaBCF** [comment]
Perfecto

**Comment by jszczerbinsky** [comment]
Done, check out latest release. I will compile it for Windows  tomorrow ;D

**Comment by OshidaBCF** [comment]
Well that was fast...

Thanks
