### ISSUE TITLE
How much .bmp are supported?

### ISSUE THREAD

**Issue by FjellrevG434** [jszczerbinsky/lwp#73]
So how much images I can stuck on top of each other? Is it going to reduce performance or there is limit on them, or it will just crash an app after some amount?

**Comment by jszczerbinsky** [comment]
App doesn't have any limit of layers count. You can have as many of them as Your computer memory can handle. If you don't have enough memory the app will crash.
Having a lot of layers will also reduce the performance, but it's hard to say how many layers are 'too much'. It depends on the computer.
