### ISSUE TITLE
Error while loading shared libraries: libconfig.so.11

### ISSUE THREAD

**Issue by DrainBread** [jszczerbinsky/lwp#77]
I'm currently running Kubuntu 22.04 LTS and I've followed the installation instructions for linux, however when I run 'lwp' I get the following error message:

lwp: error while loading shared libraries: libconfig.so.11: cannot open shared object file: No such file or directory

I've tried looking up a solution for this, but I haven´t come across a way to add this library on my system.
Did I forget a step? how can I recover from this error?

**Comment by jszczerbinsky** [comment]
You need to install `libconfig` with Your package manager.

**Comment by jszczerbinsky** [comment]
You need to install `libconfig` using Your package manager.

If the package manager can't find `libconfig`, maybe the name on the repository is different.
Try `apt search libconfig` to find the right package.
