### ISSUE TITLE
OpenSUSE Leap 15.5 support

### ISSUE THREAD

**Issue by DioKiriie** [jszczerbinsky/lwp#81]
So apparently 15.5 version of my OpenSUSE Leap is the latest one and uses glibc of version 2.31
The required version as it seems from console is 2.34.
lwp: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by lwp)

How can I run this app?

**Comment by jszczerbinsky** [comment]
I assume You're trying to run compiled version of the program (?)
Try compiling it yourself, it should link `glib` version, that Your OS has installed.
